language: php
php:
  - 5.6
  - 7.0

sudo: false

services:
  - docker

addons:
  hosts:
  - drupalcamps.dev

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --version
  - docker-compose -f docker-compose.yml build
  - docker-compose -f docker-compose.yml pull
  - docker-compose -p drupalcamps -f docker-compose.yml up > /tmp/docker-compose.log &
  # Remove ~/travis/.my.cnf. Drush picks this up and ignores settings.local.php dburl for some reason.
  - rm ~travis/.my.cnf

install:
  - composer install --prefer-dist --no-interaction
  - phantomjs --webdriver=4444 &
  - mkdir web/sites/simpletest
  - ./bin/drush --root=$(pwd)/web si conference_profile --site-name="DrupalCamps Conference" --account-pass=admin --yes
  - curl -I http://drupalcamps.dev/

script:
  - cd $TRAVIS_BUILD_DIR
  - ./bin/behat

after_failure:
  - cat /tmp/docker-compose.log