language: php
php:
  - 5.5
  - 5.6
  - 7.0

sudo: true

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
services:
  - docker
addons:
  hosts:
    - drupalcamp-base.dev

env:
  global:
    - SIMPLETEST_DB=sqlite://tmp/site.sqlite
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"
  matrix:
    - RELEASE=stable
    - RELEASE=dev
matrix:
  fast_finish: true
before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update
  - composer --version
  - docker-compose build
  - docker-compose up -d

install:
  - composer install
  - composer require drupalcamps/testing_camp

script:
  - if [[ $RELEASE = dev ]]; then composer require --no-update drupal/core:8.1.x-dev; fi;
  - if [[ $RELEASE = dev ]]; then composer update; fi;
  - ./vendor/bin/drupal --version
  - ./vendor/bin/drupal init
  - ./vendor/bin/drupal server 127.0.0.1:8080 &
  - cd $TRAVIS_BUILD_DIR/web
  - ./../vendor/bin/drupal site:install testing_camp --db-type=sqlite --db-file=sites/default/files/.ht.sqlite --no-interaction
  - sleep 3
  # Skip core/tests/Drupal/Tests/ComposerIntegrationTest.php because web/ has no composer.json
  - ./../vendor/bin/phpunit -c core --exclude-group Composer
  # Exit if the install profile didn't default.
  - ./../vendor/bin/drupal site:debug || grep -q "testing_camp" || exit 1;
