phpfpm:
    command: 'php-fpm --allow-to-run-as-root'
    image: 'mglaman/docker-php-bcmath:7.0-fpm'
    volumes:
      - './:/app'
      - './config/docker/fpm.conf:/usr/local/etc/php-fpm.conf'
      - './config/docker/php.ini:/usr/local/etc/php/conf.d/local.ini'
    links:
      - mariadb
      #- solr
      - mailhog
    environment: { APP_DOCKER: commerce2, PHP_IDE_CONFIG: serverName=commerce2.dev }
mariadb:
    command: 'mysqld --verbose'
    image: mariadb
    ports:
      - 3306
    volumes:
      - './config/docker/mysql.cnf:/etc/mysql/my.cnf'
    environment: { MYSQL_DATABASE: data, MYSQL_USER: mysql, MYSQL_PASSWORD: mysql, MYSQL_ALLOW_EMPTY_PASSWORD: 'yes', MYSQL_ROOT_PASSWORD: 'root' }
nginx:
    image: 'nginx:1.9.0'
    volumes:
      - './config/docker/nginx.conf:/etc/nginx/conf.d/default.conf'
      - './:/app'
    ports:
      - 80:80
    links:
      - phpfpm
    environment: { VIRTUAL_HOST: commerce2, APP_DOCKER: commerce2 }
#solr:
#    image: 'makuk66/docker-solr:4.10.4'
#    ports: ['8080']
#    volumes: ['./config/solr:/opt/solr/example/solr/collection1/conf']
#    entrypoint: ["/bin/bash", "-c", "/opt/solr/bin/solr -f -p 8080"]
mailhog:
    image: 'mailhog/mailhog'
    ports:
      - 8025