phpfpm:
    command: 'php-fpm --allow-to-run-as-root'
    build: docker/images/php
    volumes: ['./docker/conf/fpm.conf:/usr/local/etc/php-fpm.conf', './:/var/app', './docker/conf/php.ini:/usr/local/etc/php/conf.d/local.ini']
    links: [mariadb]
    environment: { PLATFORM_DOCKER: drupalcamp-base, PHP_IDE_CONFIG: serverName=drupalcamp-base.dev }
mariadb:
    command: 'mysqld --user=root --verbose'
    image: 'mariadb:10.1.10'
    ports: ['3306']
    volumes: ['./docker/conf/mysql.cnf:/etc/mysql/my.cnf']
    environment: { MYSQL_DATABASE: data, MYSQL_USER: mysql, MYSQL_PASSWORD: mysql, MYSQL_ALLOW_EMPTY_PASSWORD: 'yes', MYSQL_ROOT_PASSWORD: 'root' }
nginx:
    image: 'nginx:1.9.0'
    volumes: ['./docker/conf/nginx.conf:/etc/nginx/conf.d/default.conf', './:/var/app', './docker/ssl/nginx.crt:/etc/nginx/ssl/nginx.crt', './docker/ssl/nginx.key:/etc/nginx/ssl/nginx.key']
    ports: ['80', '443']
    links: [phpfpm]
    environment: { VIRTUAL_HOST: drupalcamp-base.dev, PLATFORM_DOCKER: drupalcamp-base }
