conference_attendees.settings:
  type: config_object
  label: 'Attendee settings'
  mapping:
    enable_attendee_bio:
      type: boolean
      label: 'Allow attendees to enter a bio'
    enable_organization_info:
      type: boolean
      label: 'Allow attendees to enter a bio'
    enable_dietary_preference:
      type: boolean
      label: 'Allow attendees to enter a bio'
